### ISSUE TITLE
Exclude option is will be great

### ISSUE THREAD

**Issue by tolawho** [pgmjah/filesync#1]
Sometime, I only want to sync folder to folder with exclude(file, folder) option.

**Comment by pgmjah** [comment]
Do you mean you want to ignore some sub-folders when synchronizing a root folder with children?

**Comment by pgmjah** [comment]
Feature added.

**Comment by pgmjah** [comment]
Feature added.  Can now have an "ignore" array of paths relative to the "src" directory in the sync blocks.
